/* Generated by AN DISI Unibo */ 
package it.unibo.fridge

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Fridge ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
					var food1 = 5
					var food2 = 60
					var noFood : Boolean = false
					var selectedFood = -1
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("Fridge Started")
						itunibo.coap.modelResourceCoap.create(myself ,"fridge", 5684 )
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("waitCmd") { //this:State
					action { //it:State
						noFood = false
					}
					 transition(edgeName="t00",targetState="checkingFood",cond=whenEvent("takeFood"))
				}	 
				state("checkingFood") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("takeFood(X)"), Term.createTerm("takeFood(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								selectedFood = payloadArg(0).toInt()
								if(selectedFood == 1){ if(food1 == 0){ println("NO FOOD 1 ")
								noFood = true
								 }
								 }
								else
								 { if(food2 == 0){ noFood = true
								 println("NO FOOD 2 ")
								  }
								  }
						}
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitchGuarded({noFood == true}) )
					transition( edgeName="goto",targetState="takingFood", cond=doswitchGuarded({! noFood == true}) )
				}	 
				state("takingFood") { //this:State
					action { //it:State
						println("selectedFood : $selectedFood")
						if(selectedFood == 1){ food1 = food1 - 1
						 }
						else
						 { if(selectedFood == 2){ food2 = food2 - 1
						  }
						 else
						  { println("Error")
						   }
						  }
					}
					 transition( edgeName="goto",targetState="updateModelFridge", cond=doswitch() )
				}	 
				state("updateModelFridge") { //this:State
					action { //it:State
						itunibo.robot.resourceModelSupport.updateFridgeModel(myself ,"FOOD 1: $food1; FOOD 2: $food2" )
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
			}
		}
}
