/* Generated by AN DISI Unibo */ 
package it.unibo.coapclient

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Coapclient ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("CoapClient Started")
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("waitCmd") { //this:State
					action { //it:State
					}
					 transition( edgeName="goto",targetState="interactWithFridge", cond=doswitch() )
				}	 
				state("interactWithFridge") { //this:State
					action { //it:State
						itunibo.coap.observer.resourceObserverCoapClient.create( "coap://localhost:5684/fridge"  )
					}
					 transition( edgeName="goto",targetState="takeFood1", cond=doswitch() )
				}	 
				state("takeFood1") { //this:State
					action { //it:State
						forward("takeFood", "takeFood(1)" ,"fridge" ) 
						delay(2000) 
					}
					 transition( edgeName="goto",targetState="takeFood2", cond=doswitch() )
				}	 
				state("takeFood2") { //this:State
					action { //it:State
						forward("takeFood", "takeFood(2)" ,"fridge" ) 
						delay(2000) 
					}
					 transition( edgeName="goto",targetState="takeFood1", cond=doswitch() )
				}	 
				state("interactWithPantry") { //this:State
					action { //it:State
						itunibo.coap.observer.resourceObserverCoapClient.create( "coap://localhost:5685/pantry"  )
					}
					 transition( edgeName="goto",targetState="takeDishes", cond=doswitch() )
				}	 
				state("takeDishes") { //this:State
					action { //it:State
						forward("takeDish", "takeDish(5)" ,"pantry" ) 
						delay(2000) 
					}
					 transition( edgeName="goto",targetState="takeDishes", cond=doswitch() )
				}	 
			}
		}
}
