/* Generated by AN DISI Unibo */ 
package it.unibo.flusher

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Flusher ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val FlushTimer = 2000L 
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("Start flusher")
					}
				}	 
			}
		}
}
