/* Generated by AN DISI Unibo */ 
package it.unibo.ctxResourceModel
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhostb", this, "sprint1.pl", "sysRules.pl"
	)
}

