/* Generated by AN DISI Unibo */ 
package it.unibo.maitre

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Maitre ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("Start maitre")
						delay(500) 
					}
					 transition( edgeName="goto",targetState="cmd1", cond=doswitch() )
				}	 
				state("cmd1") { //this:State
					action { //it:State
						forward("modelChange", "modelChange(robot,w)" ,"resourcemodel" ) 
					}
				}	 
			}
		}
}
