/* Generated by AN DISI Unibo */ 
package it.unibo.resourcemodel

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Resourcemodel ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						forward("local_modelChanged", "modelChanged(robot,w)" ,"mindrobot" ) 
						delay(1000) 
						forward("local_modelChanged", "modelChanged(robot,h)" ,"mindrobot" ) 
					}
				}	 
				state("oneStep") { //this:State
					action { //it:State
					}
				}	 
			}
		}
}
