/* Generated by AN DISI Unibo */ 
package it.unibo.sonarhandler

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Sonarhandler ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				var LastSonarRobot : Int = 0
				var ForLedOldSonar : Int = 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("Start Sonarhandler")
					}
					 transition(edgeName="t010",targetState="handleSonar",cond=whenEvent("sonarRobot"))
				}	 
				state("handleSonar") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("sonar(DISTANCE)"), Term.createTerm("sonar(DISTANCE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								forward("modelUpdate", "modelUpdate(sonarRobot,${payloadArg(0)})" ,"resourcemodel" ) 
								
												LastSonarRobot = Integer.parseInt( payloadArg(0) )
												val differenza = Math.abs(ForLedOldSonar-LastSonarRobot)
								if(differenza>20){ 
													ForLedOldSonar=LastSonarRobot
								forward("setLed", "setLed(1,80)" ,"leds" ) 
								 }
						}
						if( checkMsgContent( Term.createTerm("sonarLeft(DISTANCE)"), Term.createTerm("sonarLeft(DISTANCE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								forward("modelChange", "modelChange(sonarLeft,${payloadArg(0)})" ,"resourcemodel" ) 
						}
						if( checkMsgContent( Term.createTerm("sonarRigth(DISTANCE)"), Term.createTerm("sonarRigth(DISTANCE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								forward("modelChange", "modelChange(sonarRigth,${payloadArg(0)})" ,"resourcemodel" ) 
						}
						if( checkMsgContent( Term.createTerm("internalReq(TARGET)"), Term.createTerm("internalReq(TARGET)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								forward("lastSonarRobot", "lastSonarRobot($LastSonarRobot)" ,"onecellforward" ) 
						}
					}
					 transition(edgeName="t011",targetState="handleSonar",cond=whenEvent("sonar"))
					transition(edgeName="t012",targetState="handleSonar",cond=whenEvent("sonarRobot"))
					transition(edgeName="t013",targetState="handleSonar",cond=whenEvent("sonarLeft"))
					transition(edgeName="t014",targetState="handleSonar",cond=whenEvent("sonarRigth"))
					transition(edgeName="t015",targetState="handleSonar",cond=whenDispatch("internalReq"))
				}	 
			}
		}
}
