/* Generated by AN DISI Unibo */ 
package it.unibo.realsonar

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Realsonar ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				val ActualTimer : Long = 50
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("Start realSonar")
						surpluss.pollingSonar.instance(  )
						stateTimer = TimerActor("timer_s0", 
							scope, context!!, "local_tout_realsonar_s0", ActualTimer )
					}
					 transition(edgeName="t018",targetState="doNotifyAll",cond=whenTimeout("local_tout_realsonar_s0"))   
				}	 
				state("doNotifyAll") { //this:State
					action { //it:State
						val Distance = surpluss.pollingSonar.askToSonar().toInt()
						println("MY SONAR --------------> $Distance")
						if(Distance>0){ emit("sonarRobot", "sonar($Distance)" ) 
						 }
						stateTimer = TimerActor("timer_doNotifyAll", 
							scope, context!!, "local_tout_realsonar_doNotifyAll", ActualTimer )
					}
					 transition(edgeName="t019",targetState="doNotifyAll",cond=whenTimeout("local_tout_realsonar_doNotifyAll"))   
				}	 
			}
		}
}
