/* Generated by AN DISI Unibo */ 
package it.unibo.ctxResourceModelDummy
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "dummyhost2", this, "system3.pl", "sysRules.pl"
	)
}

