/* Generated by AN DISI Unibo */ 
package it.unibo.controller

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Controller ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("Send Start to explorer ")
						forward("testCmd", "testCmd(Start)" ,"explorer" ) 
						delay(6500) 
						println("Send Next to explorer ")
						forward("testCmd", "testCmd(Next)" ,"explorer" ) 
						delay(6500) 
						println("Send Next to explorer ")
						forward("testCmd", "testCmd(Next)" ,"explorer" ) 
					}
				}	 
			}
		}
}
