/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package RaspberryKotlin

class App {
    val greeting: String
        get() {
            return "Kotlin on rasp"
        }
}

fun main(args: Array<String>) {
    println(App().greeting)
}
