/* Generated by AN DISI Unibo */ 
package it.unibo.kb

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Kb ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("Start kb")
						solve("consult('robotPosResolver.pl')","") //set resVar	
					}
					 transition(edgeName="t02",targetState="handle",cond=whenDispatch("modelUpdate"))
					transition(edgeName="t03",targetState="handle",cond=whenDispatch("modelRequest"))
				}	 
				state("handle") { //this:State
					action { //it:State
						storeCurrentMessageForReply()
						if( checkMsgContent( Term.createTerm("modelRequest(TARGET,PROP)"), Term.createTerm("modelRequest(TARGET,PROP)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												var Target=payloadArg(0)
												var Prop=payloadArg(1)
								if(Target=="robot" && Prop=="location"){ solve("actualRobotPos(X,Y,O)","") //set resVar	
								if(currentSolution.isSuccess()) { 
														var X = getCurSol("X").toString()
														var Y = getCurSol("Y").toString()
														var O = getCurSol("O").toString()
								replyToCaller("modelRobotResponse", "modelRobotResponse( $X,$Y,$O )")
								 }
								else
								{ replyToCaller("modelErrorResponse", "modelErrorResponse(-1)")
								 }
								 }
								if(Target=="map"){ solve("pos($Prop,X,Y)","") //set resVar	
								if(currentSolution.isSuccess()) { 
														var X = getCurSol("X").toString()
														var Y = getCurSol("Y").toString()
								replyToCaller("modelMapResponse", "modelMapResponse( $X,$Y )")
								 }
								else
								{ replyToCaller("modelErrorResponse", "modelErrorResponse(-1)")
								 }
								 }
						}
						if( checkMsgContent( Term.createTerm("modelUpdate(TARGET,VALUE)"), Term.createTerm("modelUpdate(TARGET,VALUE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												var Target=payloadArg(0)
												var Value=payloadArg(1)
												
								if(Target=="robot"){ solve("updateRobotStateFromMove($Value)","") //set resVar	
								 }
								if(Target=="map"){ val Temp = "pos($Value,X,Y)"
								solve("updatePos($Temp)","") //set resVar	
								 }
								println("----------->KB[$Target][$Value]")
						}
					}
					 transition(edgeName="t04",targetState="handle",cond=whenDispatch("modelUpdate"))
					transition(edgeName="t05",targetState="handle",cond=whenDispatch("modelRequest"))
				}	 
			}
		}
}
