/* Generated by AN DISI Unibo */ 
package it.unibo.dishwasher

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Dishwasher ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
					var dish = 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("Dishwasher Started")
						itunibo.coap.modelResourceCoap.create(myself ,"dishwasher", 5686 )
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("waitCmd") { //this:State
					action { //it:State
					}
					 transition(edgeName="t00",targetState="puttingDish",cond=whenEvent("putDish"))
				}	 
				state("puttingDish") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("putDish(X)"), Term.createTerm("putDish(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								var X = payloadArg(0).toInt()
											  dish = dish + X
						}
					}
					 transition( edgeName="goto",targetState="updateModelDishwasher", cond=doswitch() )
				}	 
				state("updateModelDishwasher") { //this:State
					action { //it:State
						itunibo.robot.resourceModelSupport.updateDishwasherModel(myself ,"DISHES: $dish; " )
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
			}
		}
}
